name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

# Add permissions at the workflow level
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Build Electron app
      run: npm run dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List release directory (Windows)
      shell: powershell
      run: |
        echo "Release directory contents:"
        if (Test-Path "release/") {
          Get-ChildItem -Path "release/" -Force
        } else {
          echo "Release directory not found"
        }
        $executables = Get-ChildItem -Recurse -Include "*.exe", "*.dmg", "*.AppImage", "*.deb" -ErrorAction SilentlyContinue
        if ($executables) {
          $executables | ForEach-Object { $_.FullName }
        } else {
          echo "No executables found"
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: one-piece-tcg-manager-windows
        path: |
          release/
        retention-days: 30
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    # Add specific permissions for the release job
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        find artifacts -type f -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.zip" || echo "No artifacts found"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/one-piece-tcg-manager-windows/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 