name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate simple icons
      run: npm run generate-icons-simple

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Test build artifacts
      run: |
        # Check if dist directory exists and contains files
        if [ ! -d "dist" ]; then
          echo "dist directory not found"
          exit 1
        fi
        
        if [ ! -f "dist/index.html" ]; then
          echo "dist/index.html not found"
          exit 1
        fi
        
        echo "Build artifacts verified successfully"

  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate simple icons
      run: npm run generate-icons-simple

    - name: Build application
      run: npm run build

    - name: Test Electron build (without publishing)
      run: npm run dist

    - name: List build artifacts
      run: |
        echo "Build artifacts:"
        ls -la release/ || echo "No release directory found" 